seguridad/urls.py
from django.urls import path

from .views import *

app_name = 'seguridad'

urlpatterns = [
    path('login/', inicioSession, name='inicio_session'),    
    path('logout/', finSession, name='fin_session'),
]

util/urls.py
from django.urls import path
from util.views import *


app_name = 'util'

urlpatterns = [
    path('votacion_detalle/<int:pk>', VotacionDetailView.as_view(), name='votacion_detalle'),
    path('votacion_lista', VotacionListView.as_view(), name='votacion_lista'),
    path('votacion_crear', VotacionCreate.as_view(), name='votacion_crear'),
    path('votacion_actualizar/<int:pk>', VotacionUpdate.as_view(), name='votacion_actualizar'),
    path('votacion_borrar<int:pk>/delete/', VotacionDelete.as_view(), name='votacion_borrar'),
    path('votacion_resultado/<str:codigo>', votacionResultado, name='votacion_resultado'),
    path('grupo_detalle/<int:pk>', GrupoDetailView.as_view(), name='grupo_detalle'),
    path('grupo_lista', GrupoListView.as_view(), name='grupo_lista'),
    path('grupo_crear', GrupoCreate.as_view(), name='grupo_crear'),
    path('grupo_votacion_crear/<int:pk>', grupo_votacion_crear, name='grupo_votacion_crear'),
    path('grupo_actualizar/<int:pk>', GrupoUpdate.as_view(), name='grupo_actualizar'),
    path('grupo_borrar<int:pk>/delete/', GrupoDelete.as_view(), name='grupo_borrar'),
    path('candidato_detalle/<int:pk>', CandidatoDetailView.as_view(), name='candidato_detalle'),
    path('candidato_lista', CandidatoListView.as_view(), name='candidato_lista'),
    path('candidato_crear', CandidatoCreate.as_view(), name='candidato_crear'),
    path('candidato_actualizar/<int:pk>', CandidatoUpdate.as_view(), name='candidato_actualizar'),
    path('candidato_borrar<int:pk>/delete/', CandidatoDelete.as_view(), name='candidato_borrar'),    
    path('propuesta_detalle/<int:pk>', PropuestaDetailView.as_view(), name='propuesta_detalle'),
    path('propuesta_lista', PropuestaListView.as_view(), name='propuesta_lista'),
    path('propuesta_crear', PropuestaCreate.as_view(), name='propuesta_crear'),
    path('propuesta_actualizar/<int:pk>', PropuestaUpdate.as_view(), name='propuesta_actualizar'),
    path('propuesta_borrar<int:pk>/delete/', PropuestaDelete.as_view(), name='propuesta_borrar'),
    path('importar_votantes', importarVotantes, name='importar_votantes'),
    path('votante_actualizar/<int:pk>', VotanteUpdate.as_view(), name='votante_actualizar'),
    path('votante_borrar<int:pk>/delete/',VotanteDelete.as_view(), name='votante_borrar'),
]

votaciones/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from util.views import VotacionListView, votacion, votante, resultado, notificarCorreo, notificarSMS, reenviarCorreosVista

urlpatterns = [
    path('accounts/', include('seguridad.urls'), name='accounts'),
    path('', VotacionListView.as_view(), name='inicio'),
    path('admin/', admin.site.urls),    
    path('util/', include('util.urls')),
    path('resultado_<str:codigo>', resultado, name='resultado'),
    path('votacion/<str:codigo>', votacion, name='votacion'),
    path('<str:codigo>', votante, name='votante'),    
    path('notificar_correo/<str:codigo>', notificarCorreo, name='notificar_correo'),
    path('notificar_sms/<str:codigo>', notificarSMS, name='notificar_sms'),
    path('reenviar_correos/<int:pid>', reenviarCorreosVista, name='reenviar_correos'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Votaciones"

seguridad/models.py
from django.contrib.auth.models import User
from django.db import models
from empresa.models import Sucursal


class Usuario(models.Model):
    user = models.OneToOneField(User, related_name='usuario', on_delete=models.CASCADE)
    sucursal = models.ForeignKey(Sucursal, on_delete= models.CASCADE)

seguridad/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render


def inicioSession(request):
    mensaje = ""
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('inicio')
        mensaje = 'usuario o clave incorrectas, porfavor intente de nuevo'
    return render(request, 'seguridad/login.html', {'mensaje': mensaje})

def finSession(request):
    logout(request)
    return render(request, 'seguridad/login.html', {'mensaje': 'su session a finalizado'})

templates/seguridad/login.html
{% extends "index.html" %}
{% load i18n %}
{% block cuerpo_total %}
<div class="container">
<div class="row">
    <div class="col-12 p-5">
        <center>
        </br>
        </br>
        </br>
        <div class="login-panel panel panel-default w-50">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans 'Por favor identifiquese' %}</h3>
            </div>
            <div class="panel-body">
                {% if mensaje != "" %}
                <div class="alert alert-warning" role="alert">
                  {{ mensaje }}
                </div>
                {% endif %}
                <form role="form" method="post" action="{% url 'seguridad:inicio_session' %}">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <input class="form-control" placeholder="Username" name="username" type="text" autofocus>
                        </div>
                        <div class="form-group">
                            <input class="form-control" placeholder="Password" name="password" type="password" value="">
                        </div>
                        <input type="hidden" name="next" value="{{ next }}">
                        <!-- Change this to a button or input when using this as a form -->
                        <button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
                    </fieldset>
                </form>
            </div>
        </div>
        </center>
    </div>
</div>
</div>
{% endblock %}