util/urls.py
from django.urls import path
from util.views import *


app_name = 'util'

urlpatterns = [
    path('votacion_detalle/<int:pk>', VotacionDetailView.as_view(), name='votacion_detalle'),
    path('votacion_lista', VotacionListView.as_view(), name='votacion_lista'),
    path('votacion_crear', VotacionCreate.as_view(), name='votacion_crear'),
    path('votacion_actualizar/<int:pk>', VotacionUpdate.as_view(), name='votacion_actualizar'),
    path('votacion_borrar<int:pk>/delete/', VotacionDelete.as_view(), name='votacion_borrar'),
    path('votacion_resultado/<str:codigo>', votacionResultado, name='votacion_resultado'),
    path('grupo_detalle/<int:pk>', GrupoDetailView.as_view(), name='grupo_detalle'),
    path('grupo_lista', GrupoListView.as_view(), name='grupo_lista'),
    path('grupo_crear', GrupoCreate.as_view(), name='grupo_crear'),
    path('grupo_votacion_crear/<int:pk>', grupo_votacion_crear, name='grupo_votacion_crear'),
    path('grupo_actualizar/<int:pk>', GrupoUpdate.as_view(), name='grupo_actualizar'),
    path('grupo_borrar<int:pk>/delete/', GrupoDelete.as_view(), name='grupo_borrar'),
    path('candidato_detalle/<int:pk>', CandidatoDetailView.as_view(), name='candidato_detalle'),
    path('candidato_lista', CandidatoListView.as_view(), name='candidato_lista'),
    path('candidato_crear', CandidatoCreate.as_view(), name='candidato_crear'),
    path('candidato_actualizar/<int:pk>', CandidatoUpdate.as_view(), name='candidato_actualizar'),
    path('candidato_borrar<int:pk>/delete/', CandidatoDelete.as_view(), name='candidato_borrar'),    
    path('propuesta_detalle/<int:pk>', PropuestaDetailView.as_view(), name='propuesta_detalle'),
    path('propuesta_lista', PropuestaListView.as_view(), name='propuesta_lista'),
    path('propuesta_crear', PropuestaCreate.as_view(), name='propuesta_crear'),
    path('propuesta_actualizar/<int:pk>', PropuestaUpdate.as_view(), name='propuesta_actualizar'),
    path('propuesta_borrar<int:pk>/delete/', PropuestaDelete.as_view(), name='propuesta_borrar'),
    path('importar_votantes', importarVotantes, name='importar_votantes'),
    path('votante_actualizar/<int:pk>', VotanteUpdate.as_view(), name='votante_actualizar'),
    path('votante_borrar<int:pk>/delete/',VotanteDelete.as_view(), name='votante_borrar'),
]

votaciones/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from util.views import VotacionListView, votacion, votante, resultado, notificarCorreo, notificarSMS, reenviarCorreosVista

urlpatterns = [
    path('accounts/', include('seguridad.urls'), name='accounts'),
    path('', VotacionListView.as_view(), name='inicio'),
    path('admin/', admin.site.urls),    
    path('util/', include('util.urls')),
    path('resultado_<str:codigo>', resultado, name='resultado'),
    path('votacion/<str:codigo>', votacion, name='votacion'),
    path('<str:codigo>', votante, name='votante'),    
    path('notificar_correo/<str:codigo>', notificarCorreo, name='notificar_correo'),
    path('notificar_sms/<str:codigo>', notificarSMS, name='notificar_sms'),
    path('reenviar_correos/<int:pid>', reenviarCorreosVista, name='reenviar_correos'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Votaciones"

util/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.crypto import get_random_string

class Votacion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    quorum = models.IntegerField()     
    descripcion = models.TextField(null=True, blank=True, default=None) 
    terminado = models.BooleanField(default=False)
    fecha = models.DateTimeField(auto_now=True)
    fecha_apertura = models.DateTimeField()
    fecha_cierre = models.DateTimeField()  
    hash_inicio = models.CharField(max_length=64, null=True, blank=True, default=None)
    hash_fin = models.CharField(max_length=64, null=True, blank=True, default=None)
    TIPO_CHOICES = (
        ('individual', 'PROPUESTAS'),
        ('unico', 'PLANCHA/CANDIDATOS')
    )
    tipo_de_votacion = models.CharField(choices=TIPO_CHOICES, max_length=64, default='unico')
    codigo = models.CharField(max_length=32, default=None, null=True, blank=True)
    
    def __str__(self):
        return self.nombre
    
    def generarCodigo(self):
        Votacion.objects.filter(pk=self.pk).update(codigo=get_random_string(length=32))

class Grupo(models.Model):
    votacion = models.ForeignKey(Votacion, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)   
    descripcion = models.TextField(null=True, blank=True, default=None)    
    COMO_CHOICES = (
        ('si_no', 'SI / NO'),
        ('a_favor_en_contra', 'A FAVOR / EN CONTRA'),
        ('acuerdo_desacuerdo', 'ACUERDO / DESACUERDO')
    )
    votar_como = models.CharField(choices=COMO_CHOICES, max_length=64, default='si_no', blank=True)
    numero_votos_a_favor = models.IntegerField(default=0, blank=True)
    numero_votos_en_contra = models.IntegerField(default=0, blank=True)
    imagen = models.FileField(upload_to="media/img", null=True, blank=True, default=None)
    
    def __str__(self):
        return self.nombre


class Votante(models.Model):
    votacion = models.ForeignKey(Votacion, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now=True)
    telefono = models.CharField(max_length=100, null=True, blank=True, default=None)
    cedula = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100, null=True, blank=True, default=None)
    email = models.EmailField()
    notificado_sms = models.BooleanField(default=False)    
    notificado_email = models.BooleanField(default=False)
    secreto = models.CharField(max_length=100, null=True, blank=True, default=None)
    terminado = models.BooleanField(default=False)
    
    def __str__(self):
        return self.cedula
    
    def generarCodigo(self):
        Votante.objects.filter(pk=self.pk).update(secreto=get_random_string(length=32))

class Candidato(models.Model):
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to="media/img", null=True, blank=True, default=None)
    
    def __str__(self):
        return self.nombre
    
class Propuesta(models.Model):
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)   
    descripcion = models.TextField(null=True, blank=True, default=None)
    documento = models.FileField(upload_to="documentos/img", null=True, blank=True, default=None)
    
    def __str__(self):
        return self.nombre


class Voto(models.Model):
    votacion = models.ForeignKey(Votacion, on_delete=models.CASCADE)
    votante = models.OneToOneField(Votante, on_delete=models.CASCADE)    
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now=True)
    a_favor = models.BooleanField(default=False)  
    en_contra = models.BooleanField(default=False)
    secreto = models.CharField(max_length=64)
    
    def __str__(self):
        return self.secreto

util/views.py
from django.views.generic import ListView, DetailView 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils import timezone
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import Http404
from .models import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.crypto import get_random_string
import pandas
from django.conf import settings
from .helpers import *


class VotacionDetailView(LoginRequiredMixin, DetailView):
    model = Votacion

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class VotacionListView(LoginRequiredMixin, ListView):
    model = Votacion
    paginate_by = 10

    def get_queryset(self):
          return Votacion.objects.filter(usuario__pk=self.request.user.pk)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class VotacionCreate(LoginRequiredMixin, CreateView):
    model = Votacion
    form_class = VotacionForm
    
    def get_success_url(self):
        return reverse('util:votacion_actualizar', kwargs={'pk': self.object.pk})
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.usuario = self.request.user
        return super(VotacionCreate, self).form_valid(form)

class VotacionUpdate(LoginRequiredMixin, UpdateView):
    model = Votacion
    form_class = VotacionForm
    success_url = reverse_lazy('util:votacion_lista')

class VotacionDelete(LoginRequiredMixin, DeleteView):
    model = Votacion
    success_url = reverse_lazy('util:votacion_lista')


class GrupoDetailView(LoginRequiredMixin, DetailView):
    model = Grupo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context    
    
    def get_success_url(self):
        return reverse('util:grupo_detalle', kwargs={'pk': self.object.pk})


class GrupoListView(LoginRequiredMixin, ListView):
    model = Grupo
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    
    def get_queryset(self):
          return Grupo.objects.filter(votacion__usuario=self.request.user)

class GrupoCreate(LoginRequiredMixin, CreateView):
    model = Grupo
    form_class = GrupoForm
    
    def get_success_url(self):
        return reverse('util:grupo_detalle', kwargs={'pk': self.object.pk})

def grupo_votacion_crear(request, pk):
    grupo = Grupo()
    grupo.votacion_id = pk
    grupo.save()
    return redirect('util:grupo_actualizar', pk=grupo.pk)
    
class GrupoUpdate(LoginRequiredMixin, UpdateView):
    model = Grupo
    form_class = GrupoForm
    
    def get_success_url(self):
        return reverse('util:grupo_detalle', kwargs={'pk': self.object.pk})

class GrupoDelete(LoginRequiredMixin, DeleteView):
    model = Grupo    
    
    def get_success_url(self):
        return reverse('util:votacion_actualizar', kwargs={'pk': self.object.votacion.pk})

class VotanteDetailView(LoginRequiredMixin, DetailView):
    model = Votante

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class VotanteListView(LoginRequiredMixin, ListView):
    model = Votante
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class VotanteCreate(LoginRequiredMixin, CreateView):
    model = Votante
    form_class = VotanteForm
    
    def get_success_url(self):
        return reverse('util:votacion_actualizar', kwargs={'pk': self.object.votacion.pk})
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.usuario = self.request.user
        return super(VotanteCreate, self).form_valid(form)

class VotanteUpdate(LoginRequiredMixin, UpdateView):
    model = Votante
    form_class = VotanteForm
    
    def get_success_url(self):
        return reverse('util:votacion_actualizar', kwargs={'pk': self.object.votacion.pk})

class VotanteDelete(LoginRequiredMixin, DeleteView):
    model = Votante
    
    def get_success_url(self):
        return reverse('util:votacion_actualizar', kwargs={'pk': self.object.votacion.pk})

class CandidatoDetailView(LoginRequiredMixin, DetailView):
    model = Candidato

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class CandidatoListView(LoginRequiredMixin, ListView):
    model = Candidato
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class CandidatoCreate(LoginRequiredMixin, CreateView):
    model = Candidato
    form_class = CandidatoForm
    
    def get_success_url(self):
        return reverse('util:grupo_detalle', kwargs={'pk': self.object.grupo.pk})
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.usuario = self.request.user
        return super(CandidatoCreate, self).form_valid(form)

class CandidatoUpdate(LoginRequiredMixin, UpdateView):
    model = Candidato
    form_class = CandidatoForm
    
    def get_success_url(self):
        return reverse('util:grupo_detalle', kwargs={'pk': self.object.grupo.pk})

class CandidatoDelete(LoginRequiredMixin, DeleteView):
    model = Candidato
    
    def get_success_url(self):
        return reverse('util:grupo_detalle', kwargs={'pk': self.object.grupo.pk})


class PropuestaDetailView(LoginRequiredMixin, DetailView):
    model = Propuesta

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class PropuestaListView(LoginRequiredMixin, ListView):
    model = Propuesta
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class PropuestaCreate(LoginRequiredMixin, CreateView):
    model = Propuesta
    form_class = PropuestaForm
    
    def get_success_url(self):
        return reverse('util:grupo_detalle', kwargs={'pk': self.object.grupo.pk})
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.usuario = self.request.user
        return super(PropuestaCreate, self).form_valid(form)

class PropuestaUpdate(LoginRequiredMixin, UpdateView):
    model = Propuesta
    form_class = PropuestaForm
    
    def get_success_url(self):
        return reverse('util:grupo_detalle', kwargs={'pk': self.object.grupo.pk})

class PropuestaDelete(LoginRequiredMixin, DeleteView):
    model = Propuesta
    
    def get_success_url(self):
        return reverse('util:grupo_detalle', kwargs={'pk': self.object.grupo.pk})

def notificarCorreo(request, codigo):
    votante = get_object_or_404(Votante, secreto=codigo)
    mensaje = renderizarMensaje(request, votante)
    enviarCorreo(votante, mensaje)
    return redirect('util:votacion_actualizar', pk=votante.votacion.pk)

def notificarSMS(request, codigo):
    votante = get_object_or_404(Votante, secreto=codigo)
    mensaje = renderizarMensaje(request, votante)
    enviarMensaje(votante, mensaje)
    redirect('util:votacion_actualizar', pk=votante.votacion.pk)

def reenviarCorreosVista(request, pid):
    reenviarCorreos(request, pid)
    return redirect('util:votacion_actualizar', pk=pid)

def votante(request, codigo):
    votante = get_object_or_404(Votante, secreto=codigo)
    v = votante.votacion
    mensaje = ''
    if request.method == 'POST':
        if request.POST.get('cedula') == votante.cedula:
            if votante.terminado:            
                return redirect('resultado', codigo=codigo)
            else:
                return redirect('votacion', codigo=codigo)
        else:
            mensaje = 'Votante no valido'
    context = {'votacion': v, 'votante': votante, 'mensaje': mensaje}
    return render(request, 'util/seleccionar_votante.html', context)
    
def votacion(request, codigo):
    votante = get_object_or_404(Votante, secreto=codigo)
    v = votante.votacion
    if not (v.fecha_apertura < timezone.now() < v.fecha_cierre):
        raise Http404
    if request.method == 'POST' and not votante.terminado:
        if v.tipo_de_votacion == 'unico': 
            grupo = get_object_or_404(Grupo, pk=request.POST.get('grupo'))
            voto = Voto.objects.create(
                votante=votante,
                grupo_id=grupo.pk,
                a_favor=True,
                votacion=v
            )
            Grupo.objects.filter(pk=grupo.pk).update(
                        numero_votos_a_favor=(grupo.numero_votos_a_favor+1))
        elif v.tipo_de_votacion == 'individual':
            for grupo in v.grupo_set.all():
                propuesta = request.POST.get('radio'+str(grupo.pk))
                if propuesta == "1":
                    voto = Voto.objects.create(
                        votante=votante,
                        grupo=grupo,
                        votacion=v,
                        a_favor = True
                    ) 
                    Grupo.objects.filter(pk=grupo.pk).update(
                        numero_votos_a_favor=(grupo.numero_votos_a_favor+1))
                elif propuesta == "0":
                    voto = Voto.objects.create(
                        votante=votante,
                        grupo=grupo,
                        votacion=v,

templates/util/candidato_confirm_delete.html
{% extends "templates/confirmar_borrar.html" %}
{% load i18n %}
{% block titulo %}{% trans 'Producto' %}{% endblock %}

templates/util/nueva_propuesta.html
<div class="modal fade" id="propuestaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Nueva propuesta</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
       <form action="{% url 'util:propuesta_crear' %}" method="post" enctype="multipart/form-data">
      <div class="modal-body">       
        {% csrf_token %}
        <input type="hidden" value="{{ object.pk }}" name="grupo">
        <input type="text" name="nombre" class="form-control">
        <textarea class="form-control" name="descripcion"></textarea>
        <div class="custom-file">
            <input type="file" name="documento" class="custom-file-input" id="customFile">
            <label class="custom-file-label" for="customFile">Choose file</label>
        </div>        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button class="btn btn-secondary">Guardar</button>
      </div>
      </form>
    </div>
  </div>
</div>

templates/util/propuesta_detail.html
{% extends "index.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block contenido %}
<div class="container">
    <div class="section no-pad-bot" id="index-banner">
      <h3 class="header center orange-text">{% trans 'Propuesta detalle' %}</h3>
      <div class="row center">
        <h1>{{ object.nombre }}</h1>
          <a class="btn btn-sm btn-warning pull-right" href="{% url 'util:propuesta_borrar' object.pk %}">
              <i class="material-icons">delete</i>
          </a>
          <a class="btn btn-sm btn-warning pull-right" href="{% url 'util:propuesta_actualizar' object.pk %}">
              <i class="material-icons">edit</i>
          </a>
      </div>
      <br><br>
    </div>
</div>
{% endblock %}

templates/util/propuesta_form.html
{% extends "templates/formulario.html" %}
{% load i18n %}
{% block titulo %}{% trans 'Formulario propuesta' %}{% endblock %}

templates/util/propuesta_targeton.html
<div class="modal fade" id="g{{ grupo.pk }}Mod" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Propuestas</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul>
        {% for propuesta in grupo.propuesta_set.all %}
            <li>
                <h5>{{ propuesta }}</h5>
                <p>{{ propuesta.descripcion }}</p>
                <a href="{{ propuesta.imagen.url }}" target="_blank">Descargar</a>
            </li>
        {% endfor %}
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

templates/util/votacion_detail.html
{% extends "index.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block contenido %}
<div class="container">
    <div class="section no-pad-bot" id="index-banner">
      <h3 class="header center orange-text">{% trans 'Votacion detalle' %}</h3>
      <div class="row center">
        <h1>{{ object.nombre }}</h1>
        <p>{{ object.codigo }}</p>
        <p>Unidad de medida: {{ object.unidad_de_medida }}</p>
          <a class="btn btn-sm btn-warning pull-right" href="{% url 'util:votacion_borrar' object.pk %}">
              <i class="material-icons">delete</i>
          </a>
          <a class="btn btn-sm btn-warning pull-right" href="{% url 'util:votacion_actualizar' object.pk %}">
              <i class="material-icons">edit</i>
          </a>
      </div>
      <br><br>
    </div>
</div>
{% endblock %}

templates/util/votacion_form.html
{% extends "templates/formulario.html" %}
{% load static %}
{% load i18n %}
{% block titulo %}{% trans 'Formulario votacion' %}{% endblock %}
{% block tabla_asociados %}
{% if form.instance and form.instance.pk %}
    </br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {% if form.instance and form.instance.tipo_de_votacion == 'unico' %}
                    {% trans 'Lista grupos' %}
                {% else %}
                    {% trans 'Lista propuestas' %}
                {% endif %}
                <a class="btn btn-sm btn-primary float-right" href="{% url 'util:grupo_votacion_crear' form.instance.pk %}">
                    <i class="fa fa-plus"></i>
                    {% if form.instance and form.instance.tipo_de_votacion == 'unico' %}
                        {% trans 'Nuevo grupo' %}
                    {% else %}
                        {% trans 'Nueva propuesta' %}
                    {% endif %}
                </a>
            </h3>
        </div>
        <div class="panel-body">            
            {% for elemento in form.instance.grupo_set.all %}
                <div class="row">
                    <div class="col-3">
                    {% if elemento.imagen %}
                    <img src="{{ elemento.imagen.url }}" width="100%"></div>
                    {% endif %}
                    <div class="col-9">
                        <h5>{{ elemento.nombre }}</h5>
                        <p>
                            {{ elemento.descripcion }}
                            <a class="float-right" href="{% url 'util:grupo_actualizar' elemento.pk %}">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a class="float-right" href="{% url 'util:grupo_borrar' elemento.pk %}">
                                <i class="fa fa-trash"></i>
                            </a>
                        </p>
                        
                    </div>
                </div>
                <hr>
            {% endfor %}
        </div>
    </div>  
    <h6>Importar votantes - 
        <a href="#" data-toggle="modal" data-target="#exampleModal">
        actualmente: {{ form.instance.votante_set.all|length }}
        </a>
    </h6>
    <a href="{% static 'site/formato_votantes.xlsx' %}" target="_blank">Descargar Formato</a>
    <form method="post" enctype="multipart/form-data" action="{% url 'util:importar_votantes' %}">     
        {% csrf_token %}
        <input type="hidden" name="accion" value="importar_votantes">
        <input type="hidden" name="votacion" value="{{ form.instance.pk }}">
        <input type="file" name="votantes" class="form-control">
        <button type="submit" class="btn btn-sm btn-secondary float-right">Importar</button>
    </form>
    </br>
    <hr>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Votantes</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
        
            <a class="btn btns-sm btn-primary float-right" href="{% url 'reenviar_correos' form.instance.pk %}">
                <i class="fa fa-paper-plane"></i>
            </a>
            </br>
            <hr>
            {% for elemento in form.instance.votante_set.all %}
                <div class="row">
                    <div class="col-12 {% if not elemento.notificado_email %}bg-light{% endif %}">
                        <h5>{{ elemento.nombre }}</h5>
                        <p>
                            <a class="btn btns-sm btn-secondary float-right" href="{% url 'util:votante_actualizar' elemento.pk %}">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a class="btn btns-sm btn-secondary float-right" href="{% url 'util:votante_borrar' elemento.pk %}">
                                <i class="fa fa-trash"></i>
                            </a>
                            {% if elemento.secreto %}
                                <a class="btn btns-sm btn-secondary float-right" href="{% url 'notificar_correo' elemento.secreto %}">
                                    <i class="fa fa-paper-plane"></i>
                                </a>
                                <a class="btn btns-sm btn-secondary float-right" href="{% url 'notificar_sms' elemento.secreto %}">
                                    <i class="fa fa-mobile"></i>
                                </a>
                            {% endif %}
                        </p>                
                    </div>
                </div>
                <hr>
            {% endfor %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
        </div>
    </div>
    </div>
    
{% endif %}
{% endblock %}

templates/util/votacion_list (3.ª copia).html
{% extends "templates/lista.html" %}
{% load i18n %}
{% block titulo %}{% trans 'Votacion Lista' %}{% endblock %}
{% block btn_nuevo %}
    <a class="btn btn-sm btn-warning pull-right" href="{% url 'util:votacion_crear' %}">
        <i class="fa fa-plus"></i>
    </a>
{% endblock %}
{% block titulo_tabla %}
    <tr>
        <th>{% trans 'Nombre' %}</th>
    </tr>
{% endblock %}
{% block cuerpo_tabla %}
    {% for votacion in object_list %}
        <tr>
        <td> {{ votacion.nombre }}</td>
        <td>
          <a class="btn-small waves-effect waves-light orange" href="{% url 'util:votacion_actualizar' votacion.pk %}">
            <i class="fa fa-edit"></i>
          </a>
          <a class="btn-small waves-effect waves-light orange" href="{% url 'util:votacion_borrar' votacion.pk %}">
            <i class="fa fa-trash"></i>
          </a>
        </td>
        </tr>
    {% endfor %}
{% endblock %}

templates/util/votacion_list (4.ª copia).html
{% extends "templates/lista.html" %}
{% load i18n %}
{% block titulo %}{% trans 'Votacion Lista' %}{% endblock %}
{% block btn_nuevo %}
    <a class="btn btn-sm btn-warning pull-right" href="{% url 'util:votacion_crear' %}">
        <i class="fa fa-plus"></i>
    </a>
{% endblock %}
{% block titulo_tabla %}
    <tr>
        <th>{% trans 'Nombre' %}</th>
    </tr>
{% endblock %}
{% block cuerpo_tabla %}
    {% for votacion in object_list %}
        <tr>
        <td> {{ votacion.nombre }}</td>
        <td>
          <a class="btn-small waves-effect waves-light orange" href="{% url 'util:votacion_actualizar' votacion.pk %}">
            <i class="fa fa-edit"></i>
          </a>
          <a class="btn-small waves-effect waves-light orange" href="{% url 'util:votacion_borrar' votacion.pk %}">
            <i class="fa fa-trash"></i>
          </a>
        </td>
        </tr>
    {% endfor %}
{% endblock %}