util/urls.py
from django.urls import path
from util.views import *


app_name = 'util'

urlpatterns = [
    path('votacion_detalle/<int:pk>', VotacionDetailView.as_view(), name='votacion_detalle'),
    path('votacion_lista', VotacionListView.as_view(), name='votacion_lista'),
    path('votacion_crear', VotacionCreate.as_view(), name='votacion_crear'),
    path('votacion_actualizar/<int:pk>', VotacionUpdate.as_view(), name='votacion_actualizar'),
    path('votacion_borrar<int:pk>/delete/', VotacionDelete.as_view(), name='votacion_borrar'),
    path('votacion_resultado/<str:codigo>', votacionResultado, name='votacion_resultado'),
    path('grupo_detalle/<int:pk>', GrupoDetailView.as_view(), name='grupo_detalle'),
    path('grupo_lista', GrupoListView.as_view(), name='grupo_lista'),
    path('grupo_crear', GrupoCreate.as_view(), name='grupo_crear'),
    path('grupo_votacion_crear/<int:pk>', grupo_votacion_crear, name='grupo_votacion_crear'),
    path('grupo_actualizar/<int:pk>', GrupoUpdate.as_view(), name='grupo_actualizar'),
    path('grupo_borrar<int:pk>/delete/', GrupoDelete.as_view(), name='grupo_borrar'),
    path('candidato_detalle/<int:pk>', CandidatoDetailView.as_view(), name='candidato_detalle'),
    path('candidato_lista', CandidatoListView.as_view(), name='candidato_lista'),
    path('candidato_crear', CandidatoCreate.as_view(), name='candidato_crear'),
    path('candidato_actualizar/<int:pk>', CandidatoUpdate.as_view(), name='candidato_actualizar'),
    path('candidato_borrar<int:pk>/delete/', CandidatoDelete.as_view(), name='candidato_borrar'),    
    path('propuesta_detalle/<int:pk>', PropuestaDetailView.as_view(), name='propuesta_detalle'),
    path('propuesta_lista', PropuestaListView.as_view(), name='propuesta_lista'),
    path('propuesta_crear', PropuestaCreate.as_view(), name='propuesta_crear'),
    path('propuesta_actualizar/<int:pk>', PropuestaUpdate.as_view(), name='propuesta_actualizar'),
    path('propuesta_borrar<int:pk>/delete/', PropuestaDelete.as_view(), name='propuesta_borrar'),
    path('importar_votantes', importarVotantes, name='importar_votantes'),
    path('votante_actualizar/<int:pk>', VotanteUpdate.as_view(), name='votante_actualizar'),
    path('votante_borrar<int:pk>/delete/',VotanteDelete.as_view(), name='votante_borrar'),
]

votaciones/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from util.views import VotacionListView, votacion, votante, resultado, notificarCorreo, notificarSMS, reenviarCorreosVista

urlpatterns = [
    path('accounts/', include('seguridad.urls'), name='accounts'),
    path('', VotacionListView.as_view(), name='inicio'),
    path('admin/', admin.site.urls),    
    path('util/', include('util.urls')),
    path('resultado_<str:codigo>', resultado, name='resultado'),
    path('votacion/<str:codigo>', votacion, name='votacion'),
    path('<str:codigo>', votante, name='votante'),    
    path('notificar_correo/<str:codigo>', notificarCorreo, name='notificar_correo'),
    path('notificar_sms/<str:codigo>', notificarSMS, name='notificar_sms'),
    path('reenviar_correos/<int:pid>', reenviarCorreosVista, name='reenviar_correos'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Votaciones"

templates/base.html
{% load static %}
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Opsprodex</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'site/css/bootstrap/bootstrap.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'site/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />

</head>
<body>
  <div id="app">
    {% include 'templates/headers.html' %}
  <main>            
      <div class="container">
        <div class="section no-pad-bot" id="index-banner">    
          <br><br>
          {% block contenido %}
          <h1 class="header center orange-text">Starter Template</h1>
          <div class="row center">
            <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
          </div>
          <div class="row center">
            <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
          </div>
          <br><br>
          {% endblock %}
        </div>
      </div>      
  </main>
<!--
  <footer class="page-footer orange">
    <div class="container">

      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>

  </footer>-->


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
  <script src="{% static 'site/js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'site/js/vue/vue.js' %}"></script>
    <script src="{% static 'site/js/axios/axios.min.js' %}"></script>
  {% block scripts %}
  {% endblock %}
  </div>
</body>
</html>

templates/date.html
{% load crispy_forms_field %}

<div id="div_{{ field.auto_id }}" class="control-group{% if form_show_errors and field.errors %} error{% endif %} {% if field.field.widget.attrs.class %} {{ field.field.widget.attrs.class }}{% endif %}">

    {% if field.label %}
        <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
        </label>
    {% endif %}

    <div class="controls">
        <div class="input-append">
            {% crispy_field field %}
            <span class="add-on {% if active %}active{% endif %}">{{ crispy_appended_text|safe }}</span>
        </div>

        {% include 'bootstrap/layout/help_text_and_errors.html' %}
    </div>
</div>

templates/index.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% trans 'Votaciones' %}</title>
    <link href="{% static 'site/bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'site/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" type="text/css" rel="stylesheet"/>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    
    {% block menu %}{% endblock %}
    {% block cuerpo_total %}
    <div id="app">
        <div id="page-wrapper">
                <div class="container">                    
                    {% block contenido %}{% endblock %}
                </div>
            
        </div>
    </div>
    <!-- /#wrapper -->
    <script src="{% static 'site/jquery/jquery.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
    <script src="{% static 'site/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site/vue/vue.js' %}"></script>
    <script src="{% static 'site/vue/vue.js' %}"></script>
    <script src="{% static 'site/axios/axios.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
        {% block scripts %}
        {% endblock %}
    {% endblock %}
</body>

</html>

templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'inicio' %}"> Lista votaciones</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        <!-- <a class="nav-item nav-link" href="{% url 'util:grupo_lista' %}">
            Lista de grupos</a> -->
        </div>
    </div>
</nav>